<script lang="ts">
  import type { PageData } from './$types'
  let { data }: { data: PageData } = $props()
</script>
<svelte:head><title>You’re on our radar — Truewire</title><meta name="robots" content="noindex" /></svelte:head>
<section class="wrap thanks"><span class="check" aria-hidden="true">✓</span><p class="eyebrow">REQUEST RECEIVED</p><h1>{data.intent === 'cloud' ? 'You’re on the list.' : 'Let’s make something work.'}</h1><p>{data.intent === 'cloud' ? 'Your interest in Truewire Cloud is saved. We’ll contact you about early access when there’s something ready to try.' : 'Your request is saved. We’ll review what you’re building and follow up at the email address you shared.'}</p><div class="next"><h2>What happens next</h2><p>{data.intent === 'service' ? 'We’ll look at the API and access requirements, then discuss scope and pricing with you. Nothing is booked or billed by submitting this form.' : data.intent === 'cloud' ? 'Cloud is still on the roadmap. In the meantime, the open-source toolkit runs on your machine today.' : 'We’ll use the details you shared to understand where you’re stuck and what a useful next step looks like.'}</p></div><a class="btn btn-primary" href="/docs#quickstart">Try the toolkit while you wait <span aria-hidden="true">↗</span></a><a class="back" href="/">Back to Truewire</a></section>
<style>
  .thanks { max-width: 44rem; padding-block: 5rem; text-align: center; }.check { display: grid; place-items: center; width: 65px; height: 65px; border-radius: 20px; color: var(--accent); background: var(--accent-tint); font-size: 2rem; margin: 0 auto 2rem; }.eyebrow { font: .65rem var(--mono); letter-spacing: .1em; color: var(--accent); }h1 { font-size: clamp(2.5rem,5vw,4rem); letter-spacing: -.06em; }p { font-size: .9rem; color: var(--fg-muted); line-height: 1.85; }.next { text-align: left; padding: 1.5rem; border: 1px solid var(--line); background: var(--surface); border-radius: 12px; margin: 2rem 0; }.next h2 { font-size: 1.1rem; }.next p { margin: 0; }.back { display: block; font-size: .8rem; margin-top: 1.5rem; }
</style>
